base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("social/signup/", views.signup_redirect, name="signup_redirect")
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"
urlpatterns = [
    path("search/<page>", views.search, name="search"),
    path("product/<item_id>", views.product, name="product"),
    path("update_item", views.updateItem, name="update_item"),
    path("update_guest", views.updateItemGuest, name="update_item_guest")
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path("user/", include("user.urls")),
    path("items/", include("items.urls")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("request_renew", views.request_renew_password, name="request_renew"),
    path("renew/<uidb64>/<token>", views.renew_password, name="renew"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    path("", views.profile, name="profile"),
    path("password", views.user_change_password, name="password"),
    path("info", views.user_change_info, name="info"),
    path("email", views.user_change_email, name="email"),
    path("address", views.user_change_address, name="address"),
    path("delete", views.user_delete_account, name="delete"),
    path("cart", views.cart, name="cart"),
    path("order", views.order, name="order"),
    path("order/payment_successful", views.payment_successful, name="payment_successful"),
    path("order/payment_cancelled", views.payment_cancelled, name="payment_cancelled"),
    # path("stripe_webhook", views.stripe_webhook, name="stripe_webhook")
]

user/models.py
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

import json

from items.models import Item


# Create your models here.


class UserAddress(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=56)
    city = models.CharField(max_length=128)
    postal = models.CharField(max_length=16)
    street = models.CharField(max_length=128)
    number = models.CharField(max_length=16)


class Order(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    stripe_id = models.CharField(max_length=500, null=True)
    email = models.CharField(max_length=128)
    date = models.DateTimeField()
    status = models.CharField(max_length=32, default=settings.ORDER_STATUSES[0])
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    country = models.CharField(max_length=56)
    city = models.CharField(max_length=128)
    postal = models.CharField(max_length=16)
    street = models.CharField(max_length=128)
    number = models.CharField(max_length=16)

    def overall_price(self):
        price = 0.00
        items = OrderedItems.objects.values_list("quantity", "price_piece").filter(order_id=self.id)
        for item in items:
            price += item[0] * item[1]
        return price

    
class OrderedItems(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    item_id = models.ForeignKey(Item, on_delete=models.DO_NOTHING)
    quantity = models.IntegerField(default=0)
    price_piece = models.FloatField(default=1)
    
    def overall_price(self):
        return self.quantity * self.price_piece
    

class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    item_id = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def get_cart_items(request):
        if request.user.is_authenticated:
            return (Cart.objects.select_related("item_id").filter(user_id=request.user.id), Cart.get_cart_items_quantity(request))
        else:
            try:
                cart_cookie = json.loads(request.COOKIES["cart"])
            except KeyError:
                cart_cookie = {}

            cart = []
            quantity = 0
            for key, value in cart_cookie.items():
                item = {}
                item["item_id"] = Item.objects.get(id=int(key))
                item["quantity"] = value["quantity"]
                cart.append(item)
                quantity += item["quantity"]
            
            return (cart, quantity)

    
    def get_cart_items_quantity(request):
        quantity = 0
        for item in Cart.objects.filter(user_id=request.user.id):
            quantity += item.quantity
        return quantity
    
    def item_overall_price(self):
        return self.quantity*self.item_id.current_price
    
    def order_overall_price(request):
        items = Cart.objects.filter(user_id=request.user.id)
        price = 0.00
        for item in items:
            price += item.item_overall_price()
        return price
    
    def order_overall_price_not_authenticated(request):
        price = 0.0
        items = Cart.get_cart_items(request)[0]
        for item in items:
            price += (item["item_id"].current_price * item["quantity"])
        return round(price, 2)
    

class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):

    def populate_user(self, request, sociallogin, data):
        user = super().populate_user(request, sociallogin, data)
        user.username = user.email
        return user

user/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

import stripe

from .helpers import user_login, user_logout, user_register, get_user_address, get_user_orders, user_activate, renewEmail, user_renew_password, change_password, change_info, change_email, change_address, delete_account
from .helpers import get_cart_info,save_form_data, buy_user, buy_guest, order_email, check_demo_user, check_user_password, check_username
from .models import Cart, Order

from django.contrib.sites.shortcuts import get_current_site

########## VIEWS ############


def login_view(request):
    print(get_current_site(request).domain)
    if request.method == "POST":
        if user_login(request):
            response = HttpResponseRedirect(reverse("base:index"))
            response.delete_cookie("cart")
            return response
    return render(request, "user/login.html", {"cart": Cart.get_cart_items(request)})


def register(request):
    if request.method == "POST":
        if user_register(request):
            return HttpResponseRedirect(reverse("base:index"))
    return render(request, "user/register.html", {
        "cart": Cart.get_cart_items(request)
    })


def request_renew_password(request):
    if request.method == "POST":
        if request.POST["email"] == "demo@user.com":
            messages.error(request, "you can't request password change for demo user")
            return HttpResponseRedirect(reverse("user:request_renew"))
        if renewEmail(request):
            return HttpResponseRedirect(reverse("base:index"))
    return render(request, "user/request_renew_password.html", {
        "cart": Cart.get_cart_items(request)
    })


def renew_password(request, uidb64, token):
    if request.method == "POST":
        if user_renew_password(request, uidb64, token):
            return HttpResponseRedirect(reverse("user:login"))
    return render(request, "user/renew_password.html", {
        "uidb64": uidb64,
        "token": token,
        "cart": Cart.get_cart_items(request)
    })


@login_required
def profile(request):
    return render(request, "user/profile.html", {
        "user_address": get_user_address(request),
        "orders": get_user_orders(request),
        "cart": Cart.get_cart_items(request)
    })


def cart(request):
    if request.method == "POST":
        if save_form_data(request):
            return HttpResponseRedirect(reverse("user:order"))
    return render(request, "user/cart.html", get_cart_info(request))

def order(request):

    # Gets info for page render - user and cart
    context = get_cart_info(request)
    if not request.session["user_info"] or not context["cart"][0]:
        messages.error(request, "your order is incomplete")
        return HttpResponseRedirect(reverse("user:cart"))
    
    # Stripe session and payment
    if request.method == "POST":

        # Creates database entry for the order or returns to cart if theres not enough of ordered item
        if request.user.is_authenticated:
            order = buy_user(request)
        else:
            order = buy_guest(request)
        if not order:
            cart_info = get_cart_info(request)
            cart_info["user_address"] = request.session["user_info"]
            return render(request, "user/cart.html", cart_info)

        # Gets items from cart to stripe fromat
        line_items = []
        for item in context["cart"][0]:
            if request.user.is_authenticated:
                unit_amount = int(item.item_id.current_price * 100)
                name = item.item_id.name
                quantity = item.quantity
            else:
                unit_amount = int(item["item_id"].current_price * 100)
                name = item["item_id"].name
                quantity = item["quantity"]
            line_items.append({
                "price_data": {
                    "currency": "eur",
                    "unit_amount": unit_amount,
                    "product_data": {
                        "name": name
                    }
                },
                "quantity": quantity
            })
        # Creates stripe session
        stripe.api_key = settings.STRIPE_SECRET_KEY
        checkout_session = stripe.checkout.Session.create(
            payment_method_types = ["card"],
            line_items = line_items,
            mode = "payment",
            customer_creation = "always",
            success_url = settings.REDIRECT_DOMAIN + "/payment_successful?session_id={CHECKOUT_SESSION_ID}&order_id=" + str(order.id),
            cancel_url = settings.REDIRECT_DOMAIN + "/payment_cancelled",
        )

        order.stripe_id = checkout_session["id"]
        order.stauts = settings.ORDER_STATUSES[1]
        order.save()

        # Redirects to correct url and removes cart cookie
        response = HttpResponseRedirect(checkout_session.url)
        response.delete_cookie("cart")
        return response

    return render(request, "user/order.html", context)


def payment_cancelled(request):
    return render(request, "user/payment_cancelled.html")



########## FUNCTIONS ############


def payment_successful(request):
    order = Order.objects.get(id=request.GET.get("order_id", None))
    order.status = settings.ORDER_STATUSES[2]
    order.save()
    messages.success(request, "transaction successful, order created")

    order_email(request, order.email, order, order.first_name + " " + order.last_name)

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("user:profile"))
    else:
        return HttpResponseRedirect(reverse("user:cart"))


@login_required
def logout_view(request):
    user_logout(request)
    return HttpResponseRedirect(reverse("base:index"))


def activate(request, uidb64, token):
    user_activate(request, uidb64, token)
    return HttpResponseRedirect(reverse("base:index"))  


@login_required
def user_change_password(request):
    if not check_demo_user(request) and not check_user_password(request):
        change_password(request)
    return HttpResponseRedirect(reverse("user:profile"))


@login_required
def user_change_info(request):
    if not check_demo_user(request):
        change_info(request)
    return HttpResponseRedirect(reverse("user:profile"))


@login_required
def user_change_email(request):
    if not check_demo_user(request) and not check_username(request):
        change_email(request)
    return HttpResponseRedirect(reverse("user:profile"))


@login_required
def user_change_address(request):
    if not check_demo_user(request):
        change_address(request)
    return HttpResponseRedirect(reverse("user:profile"))


@login_required
def user_delete_account(request):
    if not check_demo_user(request):
        if delete_account(request):
            return HttpResponseRedirect(reverse("base:index"))
    return HttpResponseRedirect(reverse("user:profile"))

user/templates/user/cart.html
{% extends "layout_main.html" %}

{% load static %}

{% block title %}Cart{% endblock %}

{% block body %}

    <link href="{% static 'user/cart.css' %}" rel="stylesheet"> 

    <div class="navbar-space"></div>
        
    <div class="container">
        <div class="row">
            <h7>CART PAGE</h7><br><br>
        </div>
        <div class="row">
            <div class="col-lg-3 order-1">
                <div class="flex">
                    <!-- ORDER INFO -->
                    <div>
                        <p>
                            <h7>SHIPMENT:</h7>
                        </p>
                    </div>
                    <hr class="dropdown-divider">
                    {% if cart.0 %}
                        <form action="{% url 'user:cart' %}" method="post">
                            {% csrf_token %}
                            <div>
                                {% if request.user.is_authenticated %}
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="email" value="{{ request.user.email }}" placeholder="email address" disabled>
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="first_name" value="{{ request.user.first_name }}" placeholder="first name">
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="last_name" value="{{ request.user.last_name }}" placeholder="last name">
                                    </div>
                                {% else %}
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="email" value="{{ user_address.email }}" placeholder="email address">
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="first_name" value="{{ user_address.first_name }}" placeholder="first name">
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="last_name" value="{{ user_address.last_name }}" placeholder="last name">
                                    </div>
                                {% endif %}
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="street" value="{{ user_address.street }}" placeholder="street">
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="number" value="{{ user_address.number }}" placeholder="house number">
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="city" value="{{ user_address.city }}" placeholder="city">
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="postal" value="{{ user_address.postal }}" placeholder="postal code">
                                    </div>
                                    <div class="mb-3">
                                        <input type="text" class="form-control order-input" name="country" value="{{ user_address.country }}" placeholder="country">
                                    </div>
                                {% if request.user.is_authenticated and request.user.username != "demo@user.com" %}
                                    <div class="mb-3 form-check">
                                        <input type="checkbox" class="form-check-input" id="remember" name="remember" value="true">
                                        <label class="form-check-label" for="remember">update my profile</label>
                                    </div>
                                {% endif %}
                                {% if request.user.username == "demo@user.com" %}
                                    <br>
                                    <p class="align-center">
                                        Information<br><br>
                                        As a demo user, you won't be able to recive order confirmation email, although the order will still go through.
                                    </p>
                                {% endif %}
                            </div>
                            <!-- BUY BUTTON -->
                            <br><br><br>
                            <div class="svg-wrapper">
                                <svg height="60" width="100%">
                                    <rect class="shape" height="60" width="100%">
                                </svg>
                                <div class="text"><button type="submit">CHECKOUT</button></div>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
            

            <div class="col-lg-9 top-padding order-2">
                <div>
                    <p><h7>PRODUCTS:</h7></p>
                </div>
                <hr class="dropdown-divider">
                <table>
                    <tbody>
                        <tr>
                            <td scope="col">product:</td>
                            <td scope="col"></td>
                            <td scope="col">qt.:</td>
                            <td scope="col">piece price:</td>
                            <td scope="col">price:</td>
                        </tr>
                        {% for item in cart.0 %}
                            <tr>
                                <td scope="col" class="image-wrapper">
                                    <img src="{{ item.item_id.image.url }}" class="item-image">
                                </td>
                                <td scope="col"><a class="no-decorator" href="{% url 'items:product' item_id=item.item_id.id %}">{{ item.item_id.name }}</a></td>
                                <td scope="col">
                                    <button data-product="{{ item.item_id.id }}" data-action="add" class="update-cart">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-up-short" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z"/>
                                        </svg>
                                    </button><br>
                                    {{ item.quantity }}<br>
                                    <button data-product="{{ item.item_id.id }}" data-action="remove" class="update-cart">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-down-short" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z"/>
                                        </svg>
                                    </button>
                                </td>
                                <td scope="col">{{ item.item_id.current_price|floatformat:2 }}€</td>
                                <td scope="col">{{ item.item_overall_price|floatformat:2 }}€</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <th scope="col">TOTAL:</tH>
                            <th scope="col">{{ price|floatformat:2 }}€</th>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
    </div>

{% endblock %}


{% block footer %}
    {% include "footer.html" %}
{% endblock %}

user/templates/user/login.html
{% extends "layout_main.html" %}

{% load socialaccount %}

{% load static %}

{% block title %}Login{% endblock %}

{% block body %}

    <link href="{% static 'user/login.css' %}" rel="stylesheet">

    <!-- BACKGROUND -->
    <div class="bg">
        <div class="bg-wrapper">
            <img src="https://images.pexels.com/photos/3109603/pexels-photo-3109603.jpeg">
        </div>
    </div>

    <!-- CONTENT -->
    <div class="container-fluid d-flex justify-content-center">
        <div class="panel">
            <h4>SIGN IN</h4><br>
            <form action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="email" class="form-control transparent-input" name="username" placeholder="email address" autofocus>
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control transparent-input" name="password" placeholder="password">
                </div>
                <div class="questions">
                    Demo user credentials:<br>
                    email: <i>demo@user.com</i><br>
                    password: <i>demopassword</i>
                </div>
                <br><hr class="dropdown-divider">
                <br><br>
                <div class="svg-wrapper">
                    <svg height="60" width="100%">
                            <rect class="shape" height="60" width="100%">
                    </svg>
                    <div><button class="text" type="submit">SIGN IN</button></div>
                </div>
            </form>
            <br>
            <div class="questions">
                <p><a class="decorator" href="{% provider_login_url 'google'%}?next=/">Sign in with Google</a></p>
                <p><a class="decorator" href="{% url 'user:register' %}">Not a user yet? Sign up now!</a></p>
                <p><a class="decorator" href="{% url 'user:request_renew' %}">Forgot your password?</a></p>
            </div>
        </div>
    </div>

{% endblock %}

user/templates/user/mail_activation.html
{% autoescape off %}
    Hello {{ user.username }}!

    Welcome to FashionApp. Please click link below to confirm your registration:
    {{ protocol }}{{ domain }}{% url 'user:activate' uidb64=uid token=token %}

    If you didn't register in FashionApp, please ignore this message.
{% endautoescape %}

user/templates/user/mail_order.html
    <!DOCTYPE html>
    <html lang="en">

        <head>

            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <title></title>

        </head>
        
        <body>
            <div>
                Hello, {{ name }}!<br><br>
                This mail is for showcase purposes only. FashionApp does not provide a real service, it's a website that's part of mine porfolio.<br><br>
                Thank you for making an order at FashionApp. Your order was recived and it currently is beeing processed. Current order status is: {{ order.status }}.<br>
                Your shipment information:<br>
                {{ order.street }} {{ order.number }}<br>
                {{ order.city }}, {{ order.postal }}<br>
                {{ order.country }}
            </div><br>
            <div>
                <table style="word-wrap:break-word; border-collapse: collapse; width: 100%;">
                    <tbody>
                        <tr>
                            <th scope="col" style="border: none; padding: 6px; text-align: left;">ORDER DETAILS</th>
                        </tr>
                        <tr>
                            <td scope="col" style="border: none; padding: 6px; text-align: left; background-color: rgb(245, 245, 245);">product:</td>
                            <td scope="col" style="border: none; padding: 6px; text-align: center; background-color: rgb(245, 245, 245);">quantity:</td>
                            <td scope="col" style="border: none; padding: 6px; text-align: center; background-color: rgb(245, 245, 245);">piece price:</td>
                            <td scope="col" style="border: none; padding: 6px; text-align: center; background-color: rgb(245, 245, 245);">price:</td>
                        </tr>
                        {% for item in items %}
                            <tr>
                                <td scope="col" style="border: none; padding: 6px; text-align: left;"><a style="color: black;" href="https://fashionappshop.fly.dev{% url 'items:product' item_id=item.item_id.id %}">{{ item.item_id.name }}</a></td>
                                <td scope="col" style="border: none; padding: 6px; text-align: center;">{{ item.quantity }}</td>
                                <td scope="col" style="border: none; padding: 6px; text-align: center;">{{ item.item_id.current_price|floatformat:2 }}€</td>
                                <td scope="col" style="border: none; padding: 6px; text-align: center;">{{ item.overall_price|floatformat:2 }}€</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td style="border: none; padding: 6px; text-align: center; background-color: rgb(245, 245, 245);"></td>
                            <td style="border: none; padding: 6px; text-align: center; background-color: rgb(245, 245, 245);"></td>
                            <th scope="col" style="border: none; padding: 6px; text-align: center; background-color: rgb(245, 245, 245);">TOTAL:</tH>
                            <th scope="col" style="border: none; padding: 6px; text-align: center; background-color: rgb(245, 245, 245);">{{ order.overall_price|floatformat:2 }}€</th>
                        </tr>
                    </tbody>
                </table>
            </div><br><br>
            <div>
                {% if order.user_id %}
                    You can check your order in your profile page.
                {% endif %}
                Thank you for trying out my application.<br><br>
                Best regards, app's developer.
            </div>
        </body>
    
</html>

user/templates/user/mail_renew_password.html
{% autoescape off %}
    Hello {{ user }}!

    This is FashionApp. You have requested a password renewal. Please follow the link below:
    {{ protocol }}{{ domain }}{% url 'user:renew' uidb64=uid token=token %}

    If you haven't requested a password renewal in FashionApp, please ignore this message.
{% endautoescape %}

user/templates/user/payment_cancelled.html
{% extends "layout_main.html" %}

{% load static %}

{% block title %}Cancelled{% endblock %}

{% block body %}

    <link href="{% static 'user/payment_cancelled.css' %}" rel="stylesheet"> 

    <div class="navbar-space"></div>

    <div class="container">
        <h2>Something went wrong and your payment didn't go through.</h2>
    </div>

{% endblock %}


{% block footer %}
    {% include "footer.html" %}
{% endblock %}

user/templates/user/renew_password.html
{% extends "layout_main.html" %}

{% load static %}

{% block title %}Renew password{% endblock %}

{% block body %}

    <link href="{% static 'user/renew_password.css' %}" rel="stylesheet">

    <!-- BACKGROUND -->
    <div class="bg">
        <div class="bg-wrapper">
            <img src="https://images.pexels.com/photos/3109603/pexels-photo-3109603.jpeg">
        </div>
    </div>

    <!-- CONTENT -->
    <div class="container-fluid d-flex justify-content-center">
        <div class="panel">
            <h4>RENEW PASSWORD</h4><br>
            <form action="{% url 'user:renew' uidb64=uidb64 token=token %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="password" autofocus>
                    <div id="passwordHelp" class="form-text">
                        <ul>
                            <li>at least 8 characters long</li>
                            <li>not similar to email address</li>
                            <li>not among commonly used passwords</li>
                        </ul>
                    </div>
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control" name="repeat_password" placeholder="repeat password">
                </div>
                <br><hr class="dropdown-divider">
                <br><br>
                <div class="svg-wrapper">
                    <svg height="60" width="100%">
                            <rect class="shape" height="60" width="100%">
                    </svg>
                    <div><button class="text" type="submit">SUBMIT</button></div>
                </div>
            </form>
            <br>
        </div>
    </div>

{% endblock %}