base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("social/signup/", views.signup_redirect, name="signup_redirect")
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"
urlpatterns = [
    path("search/<page>", views.search, name="search"),
    path("product/<item_id>", views.product, name="product"),
    path("update_item", views.updateItem, name="update_item"),
    path("update_guest", views.updateItemGuest, name="update_item_guest")
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path("user/", include("user.urls")),
    path("items/", include("items.urls")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("request_renew", views.request_renew_password, name="request_renew"),
    path("renew/<uidb64>/<token>", views.renew_password, name="renew"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    path("", views.profile, name="profile"),
    path("password", views.user_change_password, name="password"),
    path("info", views.user_change_info, name="info"),
    path("email", views.user_change_email, name="email"),
    path("address", views.user_change_address, name="address"),
    path("delete", views.user_delete_account, name="delete"),
    path("cart", views.cart, name="cart"),
    path("order", views.order, name="order"),
    path("order/payment_successful", views.payment_successful, name="payment_successful"),
    path("order/payment_cancelled", views.payment_cancelled, name="payment_cancelled"),
    # path("stripe_webhook", views.stripe_webhook, name="stripe_webhook")
]

templates/footer.html
<footer class="layout-footer">
    <p class="footer-text">
        Thank you for trying out my application. If you'd like to get in touch with me, you can find contact information in about page.<br>
        <a href="{% url 'base:about' %}">about</a>
    </p>
</footer>

templates/layout_main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <title>FashionApp: {% block title %}{% endblock %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

         <!-- Bootstrap -->
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
        <script type="text/javascript">

            var user = "{{ request.user }}"

            function getToken(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            const csrftoken = getToken('csrftoken');



            function getCookie(name) {
                // Split cookie string and get all individual name=value pairs in an array
                var cookieArr = document.cookie.split(";")

                // Loop through the array elements
                for(var i =0; i < cookieArr.length; i++) {
                    var cookiePair = cookieArr[i].split("=")

                    /* Removing whitespace at the begining of cookie name and compare it with the given string */
                    if(name == cookiePair[0].trim()) {
                        // Decode the cookie value and return
                        return decodeURIComponent(cookiePair[1])
                    }
                }

                // Return null if not found
                return null
            }
            var cart = JSON.parse(getCookie("cart"))
            if(cart == undefined) {
                cart = {}
                console.log("Cart was created!")
                document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/"
            }

            console.log("Cart: ", cart)

        </script>

    </head>
    <body>

        <link href="{% static 'style/layout_main.css' %}" rel="stylesheet"> 

        <div class="layout-main">

            <!-- Page navigation -->
            <nav class="navbar navbar-expand-lg navbar-dark custom-transparent fixed-top">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'base:index' %}">F A S H I O N</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'items:search' page=1 %}">shop</a>
                                </li>

                                <div class="dropdown">
                                    <a class="nav-item nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">cart({{ cart.1 }})</a>
                                    <ul class="dropdown-menu dropdown-menu-dark custom-almost-transparent" aria-labelledby="navbarDropdown">
                                        {% if not cart %}
                                            <li><a class="dropdown-item custom-onclick" href="#">empty</a></li>
                                        {% else %}
                                            {% for item in cart.0 %}
                                                <li><a class="dropdown-item custom-onclick" href="{% url 'items:product' item_id=item.item_id.id %}">{{ item.item_id.name }} - {{ item.quantity }}</a></li>
                                            {% endfor %}
                                        {% endif %}
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item custom-onclick" href="{% url 'user:cart' %}">go to cart</a></li>
                                    </ul>
                                </div>
                                <div class="dropdown">
                                    <a class="nav-item nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">profile</a>
                                    <ul class="dropdown-menu dropdown-menu-dark custom-almost-transparent" aria-labelledby="navbarDropdown">
                                        {% if user.is_authenticated %}
                                            <li><a class="dropdown-item custom-onclick" href="{% url 'user:profile' %}">your profile</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item custom-onclick" href="{% url 'user:logout' %}">logout</a></li>
                                        {% else %}
                                            <li><a class="dropdown-item custom-onclick" href="{% url 'user:login' %}">login</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item custom-onclick" href="{% url 'user:register' %}">register</a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'base:about' %}">about</a>
                                </li>
                                
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <!-- Alert messages -->
            {% if messages %}
            <div class="container alert-container">
                <div class="positioning">
                    <div class="alert alert-secondary alert-dismissible fade show" role="alert">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            </div>
            {% endif %}

            <!-- Page content -->
            {% block body %}

            {% endblock %}

        </div>

        <!-- Footer -->
        {% block footer %}

        {% endblock %}

        <script type="text/javascript" src="{% static 'script/cart.js' %}"></script>    

    </body>
</html>